mv ABP\(BW\)_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    ABP_BW__Onebit__datasize2_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv ABP\(BW\)_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz	    ABP_BW__Onebit__datasize2_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv ABP\(BW\)_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    ABP_BW__Onebit__datasize2_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv ABP\(BW\)_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    ABP_BW__Onebit__datasize3_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv ABP\(BW\)_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz	    ABP_BW__Onebit__datasize3_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv ABP\(BW\)_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    ABP_BW__Onebit__datasize3_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv ABP_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    ABP_Onebit__datasize2_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv ABP_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz		    ABP_Onebit__datasize2_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv ABP_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    ABP_Onebit__datasize2_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv ABP_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    ABP_Onebit__datasize3_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv ABP_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz		    ABP_Onebit__datasize3_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv ABP_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    ABP_Onebit__datasize3_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    Buffer_Onebit__datasize2_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz	    Buffer_Onebit__datasize2_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    Buffer_Onebit__datasize2_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=2_windowsize\=1\)eq\=branching-bisim.mpg.gz	    Buffer_Onebit__datasize2_capacity2_windowsize1_eqbranching-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=2_windowsize\=1\)eq\=branching-sim.mpg.gz	    Buffer_Onebit__datasize2_capacity2_windowsize1_eqbranching-sim.mpg.gz
mv Buffer_Onebit_\(datasize\=2_capacity\=2_windowsize\=1\)eq\=weak-bisim.mpg.gz		    Buffer_Onebit__datasize2_capacity2_windowsize1_eqweak-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    Buffer_Onebit__datasize3_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz	    Buffer_Onebit__datasize3_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    Buffer_Onebit__datasize3_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=2_windowsize\=1\)eq\=branching-bisim.mpg.gz	    Buffer_Onebit__datasize3_capacity2_windowsize1_eqbranching-bisim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=2_windowsize\=1\)eq\=branching-sim.mpg.gz	    Buffer_Onebit__datasize3_capacity2_windowsize1_eqbranching-sim.mpg.gz
mv Buffer_Onebit_\(datasize\=3_capacity\=2_windowsize\=1\)eq\=weak-bisim.mpg.gz		    Buffer_Onebit__datasize3_capacity2_windowsize1_eqweak-bisim.mpg.gz
mv CABP_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=strong-bisim.mpg.gz		    CABP_Onebit__datasize2_capacity1_windowsize1_eqstrong-bisim.mpg.gz
mv CABP_Onebit_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=strong-bisim.mpg.gz		    CABP_Onebit__datasize3_capacity1_windowsize1_eqstrong-bisim.mpg.gz
mv CABP_SWP_\(datasize\=4_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz		    CABP_SWP__datasize4_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv CABP_SWP_\(datasize\=4_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz		    CABP_SWP__datasize4_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv CABP_SWP_\(datasize\=4_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    CABP_SWP__datasize4_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv Hesselink_\(Implementation\)_Hesselink_\(Specification\)_\(datasize\=2\)eq\=branching-bisim.mpg.gz	    Hesselink__Implementation__Hesselink__Specification___datasize2_eqbranching-bisim.mpg.gz
mv Hesselink_\(Implementation\)_Hesselink_\(Specification\)_\(datasize\=2\)eq\=branching-sim.mpg.gz	    Hesselink__Implementation__Hesselink__Specification___datasize2_eqbranching-sim.mpg.gz
mv Hesselink_\(Implementation\)_Hesselink_\(Specification\)_\(datasize\=2\)eq\=weak-bisim.mpg.gz		    Hesselink__Implementation__Hesselink__Specification___datasize2_eqweak-bisim.mpg.gz
mv Hesselink_\(Specification\)_Hesselink_\(Implementation\)_\(datasize\=2\)eq\=branching-bisim.mpg.gz	    Hesselink__Specification__Hesselink__Implementation___datasize2_eqbranching-bisim.mpg.gz
mv Hesselink_\(Specification\)_Hesselink_\(Implementation\)_\(datasize\=2\)eq\=branching-sim.mpg.gz	    Hesselink__Specification__Hesselink__Implementation___datasize2_eqbranching-sim.mpg.gz
mv Hesselink_\(Specification\)_Hesselink_\(Implementation\)_\(datasize\=2\)eq\=weak-bisim.mpg.gz		    Hesselink__Specification__Hesselink__Implementation___datasize2_eqweak-bisim.mpg.gz
mv Onebit_SWP_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=strong-bisim.mpg.gz		    Onebit_SWP__datasize2_capacity1_windowsize1_eqstrong-bisim.mpg.gz
mv Onebit_SWP_\(datasize\=3_capacity\=1_windowsize\=1\)eq\=strong-bisim.mpg.gz		    Onebit_SWP__datasize3_capacity1_windowsize1_eqstrong-bisim.mpg.gz
mv Par_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-bisim.mpg.gz	    Par_Onebit__datasize2_capacity1_windowsize1_eqbranching-bisim.mpg.gz
mv Par_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=branching-sim.mpg.gz		    Par_Onebit__datasize2_capacity1_windowsize1_eqbranching-sim.mpg.gz
mv Par_Onebit_\(datasize\=2_capacity\=1_windowsize\=1\)eq\=weak-bisim.mpg.gz		    Par_Onebit__datasize2_capacity1_windowsize1_eqweak-bisim.mpg.gz
mv SWP_SWP_\(datasize\=2_capacity\=1_windowsize\=2\)eq\=branching-bisim.mpg.gz		    SWP_SWP__datasize2_capacity1_windowsize2_eqbranching-bisim.mpg.gz
mv SWP_SWP_\(datasize\=2_capacity\=1_windowsize\=2\)eq\=branching-sim.mpg.gz		    SWP_SWP__datasize2_capacity1_windowsize2_eqbranching-sim.mpg.gz
mv SWP_SWP_\(datasize\=2_capacity\=1_windowsize\=2\)eq\=strong-bisim.mpg.gz		    SWP_SWP__datasize2_capacity1_windowsize2_eqstrong-bisim.mpg.gz
mv SWP_SWP_\(datasize\=2_capacity\=1_windowsize\=2\)eq\=weak-bisim.mpg.gz		    SWP_SWP__datasize2_capacity1_windowsize2_eqweak-bisim.mpg.gz
mv SWP_SWP_\(datasize\=3_capacity\=1_windowsize\=2\)eq\=strong-bisim.mpg.gz		    SWP_SWP__datasize3_capacity1_windowsize2_eqstrong-bisim.mpg.gz
