mv BRPdatasize\=2_counting.mpg.gz			BRPdatasize2_counting.mpg.gz
mv Clobberwidth\=4_height\=4_black_has_winning_strategy.mpg.gz			Clobberwidth4_height4_black_has_winning_strategy.mpg.gz
mv Clobberwidth\=4_height\=4_white_has_winning_strategy.mpg.gz			Clobberwidth4_height4_white_has_winning_strategy.mpg.gz
mv Hanoindisks\=12_eventually_done.mpg.gz			Hanoindisks12_eventually_done.mpg.gz
mv Hanoindisks\=13_eventually_done.mpg.gz			Hanoindisks13_eventually_done.mpg.gz
mv Hesselinkdatasize\=2_nodeadlock.mpg.gz			Hesselinkdatasize2_nodeadlock.mpg.gz
mv Hesselinkdatasize\=2_property1.mpg.gz			Hesselinkdatasize2_property1.mpg.gz
mv Hesselinkdatasize\=2_property2.mpg.gz			Hesselinkdatasize2_property2.mpg.gz
mv Hesselinkdatasize\=3_nodeadlock.mpg.gz			Hesselinkdatasize3_nodeadlock.mpg.gz
mv Hesselinkdatasize\=3_property2.mpg.gz			Hesselinkdatasize3_property2.mpg.gz
mv IEEE1394nparties\=2_datasize\=2_headersize\=2_acksize\=2_property3.mpg.gz			IEEE1394nparties2_datasize2_headersize2_acksize2_property3.mpg.gz
mv IEEE1394nparties\=2_datasize\=2_headersize\=2_acksize\=2_property4.mpg.gz			IEEE1394nparties2_datasize2_headersize2_acksize2_property4.mpg.gz
mv IEEE1394nparties\=2_datasize\=2_headersize\=2_acksize\=2_property5.mpg.gz			IEEE1394nparties2_datasize2_headersize2_acksize2_property5.mpg.gz
mv Leadernparticipants\=4_eventually-stable.mpg.gz			Leadernparticipants4_eventually-stable.mpg.gz
mv Lift_\(Incorrect\)nlifts\=4_liveness_1_1.mpg.gz			Lift__Incorrect_nlifts4_liveness_1_1.mpg.gz
mv Lift_\(Incorrect\)nlifts\=4_liveness_1_2.mpg.gz			Lift__Incorrect_nlifts4_liveness_1_2.mpg.gz
mv Lift_\(Incorrect\)nlifts\=4_nodeadlock.mpg.gz			Lift__Incorrect_nlifts4_nodeadlock.mpg.gz
mv Lift_\(Incorrect\)nlifts\=4_safety_1.mpg.gz			Lift__Incorrect_nlifts4_safety_1.mpg.gz
mv Onebitdatasize\=3_invariantly_infinitely_many_reachable_taus.mpg.gz			Onebitdatasize3_invariantly_infinitely_many_reachable_taus.mpg.gz
mv Onebitdatasize\=3_message_can_be_lost_infinitely_often.mpg.gz			Onebitdatasize3_message_can_be_lost_infinitely_often.mpg.gz
mv Onebitdatasize\=3_messages_can_be_overtaken.mpg.gz			Onebitdatasize3_messages_can_be_overtaken.mpg.gz
mv Onebitdatasize\=3_messages_read_are_inevitably_sent.mpg.gz			Onebitdatasize3_messages_read_are_inevitably_sent.mpg.gz
mv Onebitdatasize\=3_no_duplication_of_messages.mpg.gz			Onebitdatasize3_no_duplication_of_messages.mpg.gz
mv Onebitdatasize\=3_no_spontaneous_messages.mpg.gz			Onebitdatasize3_no_spontaneous_messages.mpg.gz
mv Onebitdatasize\=3_read_then_eventually_send.mpg.gz			Onebitdatasize3_read_then_eventually_send.mpg.gz
mv SWPdatasize\=2_windowsize\=3_infinitely_often_receive_for_all_d.mpg.gz			SWPdatasize2_windowsize3_infinitely_often_receive_for_all_d.mpg.gz
mv SWPdatasize\=2_windowsize\=3_invariantly_infinitely_many_reachable_taus.mpg.gz			SWPdatasize2_windowsize3_invariantly_infinitely_many_reachable_taus.mpg.gz
mv SWPdatasize\=2_windowsize\=3_no_duplication_of_messages.mpg.gz			SWPdatasize2_windowsize3_no_duplication_of_messages.mpg.gz
mv SWPdatasize\=2_windowsize\=3_read_then_eventually_send_if_fair.mpg.gz			SWPdatasize2_windowsize3_read_then_eventually_send_if_fair.mpg.gz
mv SWPdatasize\=2_windowsize\=3_read_then_eventually_send.mpg.gz			SWPdatasize2_windowsize3_read_then_eventually_send.mpg.gz
mv SWPdatasize\=2_windowsize\=4_infinitely_often_receive_d1.mpg.gz			SWPdatasize2_windowsize4_infinitely_often_receive_d1.mpg.gz
mv SWPdatasize\=2_windowsize\=4_infinitely_often_receive_for_all_d.mpg.gz			SWPdatasize2_windowsize4_infinitely_often_receive_for_all_d.mpg.gz
mv SWPdatasize\=2_windowsize\=4_invariantly_infinitely_many_reachable_taus.mpg.gz			SWPdatasize2_windowsize4_invariantly_infinitely_many_reachable_taus.mpg.gz
mv SWPdatasize\=2_windowsize\=4_nodeadlock.mpg.gz			SWPdatasize2_windowsize4_nodeadlock.mpg.gz
mv SWPdatasize\=2_windowsize\=4_no_duplication_of_messages.mpg.gz			SWPdatasize2_windowsize4_no_duplication_of_messages.mpg.gz
mv SWPdatasize\=2_windowsize\=4_read_then_eventually_send_if_fair.mpg.gz			SWPdatasize2_windowsize4_read_then_eventually_send_if_fair.mpg.gz
mv SWPdatasize\=2_windowsize\=4_read_then_eventually_send.mpg.gz			SWPdatasize2_windowsize4_read_then_eventually_send.mpg.gz
mv SWPdatasize\=4_windowsize\=2_infinitely_often_receive_for_all_d.mpg.gz			SWPdatasize4_windowsize2_infinitely_often_receive_for_all_d.mpg.gz
mv SWPdatasize\=4_windowsize\=2_no_duplication_of_messages.mpg.gz			SWPdatasize4_windowsize2_no_duplication_of_messages.mpg.gz
mv SWPdatasize\=4_windowsize\=2_read_then_eventually_send.mpg.gz			SWPdatasize4_windowsize2_read_then_eventually_send.mpg.gz
mv SWPdatasize\=4_windowsize\=3_infinitely_often_receive_d1.mpg.gz			SWPdatasize4_windowsize3_infinitely_often_receive_d1.mpg.gz
mv SWPdatasize\=4_windowsize\=3_invariantly_infinitely_many_reachable_taus.mpg.gz			SWPdatasize4_windowsize3_invariantly_infinitely_many_reachable_taus.mpg.gz
mv SWPdatasize\=4_windowsize\=3_nodeadlock.mpg.gz			SWPdatasize4_windowsize3_nodeadlock.mpg.gz
mv SWPdatasize\=4_windowsize\=3_no_generation_of_messages.mpg.gz			SWPdatasize4_windowsize3_no_generation_of_messages.mpg.gz
mv SWPdatasize\=4_windowsize\=3_read_then_eventually_send_if_fair.mpg.gz			SWPdatasize4_windowsize3_read_then_eventually_send_if_fair.mpg.gz
